repos:
  - repo: local
    hooks:
      - id: lint_fix
        name: Fix linting issues
        entry: uv run ruff check --fix .
        language: system
        pass_filenames: false
        require_serial: true
      - id: check_formatter
        name: Check python formatting
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
        require_serial: true
      - id: check_linter
        name: Check with linter
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        require_serial: true 